### PR TITLE
fixes JustGiving/JustGiving.EventStore.Http#21

### PR DESCRIPTION
**Pull request by robvdlv**
Hi,

Was doubting whether that was something you'd consider;
Yes that would cut it :)

Rob

### CODE REVIEW

**Comment by spadger** [comment]
CI build is a little sad right now so it will be a little while until it reaches Nigeria (certainly not today)

**Comment by spadger** [comment]
Nuget...

**Comment by spadger** [comment]
Pushed v1.0.160...

**Comment by robvdlv** [comment]
Appreciated!

**Pull request merged**
